import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, CheckCircle, Award, AlertCircle, List, Download, Printer, Lightbulb, Sparkles, Loader } from 'lucide-react';
import api, { fileUrl } from '../api';

// Opens a clean, printable feedback document in a new window and triggers the
// browser's print dialog (the user picks "Save as PDF"). Same pattern the rest
// of the app uses for PDFs — no server-side PDF library required.
function openFeedbackPrintWindow(data) {
    const { student, feedback, wrong_answers = [] } = data;
    const esc = (s) => String(s ?? '').replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));

    const mistakesHtml = (feedback.key_mistakes || []).map((m, i) => `
        <div class="mistake">
            <div class="mistake-topic">${i + 1}. ${esc(m.topic)}</div>
            <div class="mistake-row"><b>What went wrong:</b> ${esc(m.what_went_wrong)}</div>
            <div class="mistake-row"><b>Why:</b> ${esc(m.why)}</div>
        </div>`).join('');

    const planHtml = (feedback.improvement_plan || []).map(s => `<li>${esc(s)}</li>`).join('');
    const reviseHtml = (feedback.topics_to_revise || []).map(t => `<span class="chip">${esc(t)}</span>`).join('');
    const tableRows = wrong_answers.map(q => `
        <tr>
            <td>${esc(q.q_num)}</td>
            <td>${esc(q.topic)}</td>
            <td>${esc(q.teacher_tip)}</td>
        </tr>`).join('');

    const html = `<!doctype html><html><head><meta charset="utf-8"><title>Feedback — ${esc(student.student_id)}</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; color: #1f2937; max-width: 800px; margin: 0 auto; padding: 40px; line-height: 1.6; }
        .header { text-align: center; border-bottom: 3px solid #4f46e5; padding-bottom: 16px; margin-bottom: 8px; }
        .header h1 { color: #4f46e5; margin: 0 0 6px; font-size: 24px; }
        .meta { color: #6b7280; font-size: 14px; }
        .score { display: inline-block; background: #4f46e5; color: #fff; padding: 6px 16px; border-radius: 20px; font-weight: 700; margin-top: 8px; }
        h2 { color: #4f46e5; font-size: 17px; margin: 24px 0 8px; border-left: 4px solid #4f46e5; padding-left: 10px; }
        .assessment { background: #f5f3ff; border-radius: 10px; padding: 14px 18px; font-size: 15px; }
        .mistake { background: #fef2f2; border-left: 3px solid #ef4444; border-radius: 0 8px 8px 0; padding: 10px 14px; margin-bottom: 10px; }
        .mistake-topic { font-weight: 700; color: #b91c1c; margin-bottom: 4px; }
        .mistake-row { font-size: 14px; }
        ul { margin: 6px 0; padding-left: 22px; }
        li { margin-bottom: 6px; }
        .chip { display: inline-block; background: #e0e7ff; color: #4338ca; padding: 4px 12px; border-radius: 16px; font-size: 13px; font-weight: 600; margin: 3px; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 8px; }
        th { background: #4f46e5; color: #fff; padding: 8px 10px; text-align: left; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
        .encourage { background: #ecfdf5; border-left: 3px solid #10b981; border-radius: 0 8px 8px 0; padding: 14px 18px; margin-top: 20px; font-style: italic; color: #047857; }
        .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 30px; border-top: 1px solid #e5e7eb; padding-top: 12px; }
        @media print { body { padding: 20px; } .noprint { display: none; } }
    </style></head><body>
        <div class="header">
            <h1>📚 Your Feedback & Improvement Plan</h1>
            <div class="meta"><b>${esc(student.student_id)}</b> · ${esc(student.grade)} · ${esc(student.subject)} · ${esc(student.exam)}</div>
            <div class="score">Score: ${esc(student.total_marks)}/${esc(student.max_marks)} (${esc(student.percentage)}%)</div>
        </div>

        <h2>Overall Assessment</h2>
        <div class="assessment">${esc(feedback.overall_assessment)}</div>

        ${mistakesHtml ? `<h2>Key Mistakes</h2>${mistakesHtml}` : ''}
        ${planHtml ? `<h2>Your Improvement Plan</h2><ul>${planHtml}</ul>` : ''}
        ${reviseHtml ? `<h2>Topics to Revise</h2><div>${reviseHtml}</div>` : ''}
        ${tableRows ? `<h2>Questions to Practice</h2><table><thead><tr><th>Q</th><th>Topic</th><th>Tip</th></tr></thead><tbody>${tableRows}</tbody></table>` : ''}

        <div class="encourage">💪 ${esc(feedback.encouragement)}</div>

        <div class="footer">Generated by MarkNex AI · Keep practicing — every mistake is a step forward!</div>

        <div class="noprint" style="text-align:center; margin-top:24px;">
            <button onclick="window.print()" style="background:#4f46e5;color:#fff;border:none;padding:12px 28px;border-radius:8px;font-size:15px;cursor:pointer;">🖨️ Save as PDF / Print</button>
        </div>
    </body></html>`;

    const w = window.open('', '_blank');
    if (!w) { alert('Please allow pop-ups to view the feedback document.'); return; }
    w.document.write(html);
    w.document.close();
}

function Report() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [script, setScript] = useState(null);
    const [aiCorrections, setAiCorrections] = useState([]);
    const [questionsAnalysis, setQuestionsAnalysis] = useState([]);
    const [activeMistake, setActiveMistake] = useState(null);
    const [generatingFeedback, setGeneratingFeedback] = useState(false);
    const scrollContainerRef = React.useRef(null);

    useEffect(() => {
        if (activeMistake !== null && aiCorrections[activeMistake] && scrollContainerRef.current) {
            const corr = aiCorrections[activeMistake];
            const container = scrollContainerRef.current;
            // Calculate scroll position based on percentage
            const targetY = (corr.y / 100) * container.scrollHeight;
            const targetX = (corr.x / 100) * container.scrollWidth;

            container.scrollTo({
                top: targetY - (container.clientHeight / 2),
                left: targetX - (container.clientWidth / 2),
                behavior: 'smooth'
            });
        }
    }, [activeMistake, aiCorrections]);

    useEffect(() => {
        const fetchScript = async () => {
            try {
                const res = await api.get('/scripts');
                const found = res.data.find(s => s.id === parseInt(id));
                setScript(found);
                if (found?.corrections) {
                    try { setAiCorrections(JSON.parse(found.corrections)); } catch (e) {}
                }
                if (found?.question_analysis) {
                    try { setQuestionsAnalysis(JSON.parse(found.question_analysis)); } catch (e) {}
                }
            } catch (err) {
                console.error(err);
            }
        };
        fetchScript();
    }, [id]);

    const generateFeedbackPDF = async () => {
        setGeneratingFeedback(true);
        try {
            const { data } = await api.post(`/scripts/${id}/feedback-pdf`, {});

            if (data.message && !data.feedback) {
                alert(data.message);  // e.g. "No wrong answers — excellent work! ✓"
                return;
            }

            openFeedbackPrintWindow(data);
        } catch (err) {
            alert('Failed to generate feedback: ' + (err.response?.data?.error || err.message));
        } finally {
            setGeneratingFeedback(false);
        }
    };

    if (!script) return <div style={{ padding: '2rem', textAlign: 'center' }}>Loading...</div>;

    return (
        <div style={{ animation: 'fadeIn 0.5s ease', maxWidth: '900px', margin: '0 auto', paddingBottom: '3rem' }}>
            <style>
                {`
                    @media print {
                        body { background: white !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                        .no-print { display: none !important; }
                        .report-card-print { 
                            box-shadow: none !important; 
                            border: none !important; 
                            padding: 0 !important; 
                            width: 100% !important;
                            max-width: none !important;
                            margin: 0 !important;
                        }
                        #corrections-container { 
                            height: auto !important; 
                            max-height: none !important; 
                            overflow: visible !important; 
                            border: none !important;
                            background: white !important;
                        }
                        .page-break { page-break-before: always; }
                        .report-section { margin-top: 2rem; border-top: 2px solid #eee; padding-top: 2rem; }
                        .marker-dot { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                    }
                `}
            </style>

            <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1.5rem', alignItems: 'center', padding: '0 1rem' }}>
                <button
                    onClick={() => navigate('/dashboard')}
                    className="btn"
                    style={{ background: 'transparent', color: 'var(--text-muted)', padding: '0.5rem 0' }}>
                    <ArrowLeft size={18} /> Back to Dashboard
                </button>
                <div style={{ display: 'flex', gap: '0.75rem' }}>
                    <button
                        onClick={generateFeedbackPDF}
                        disabled={generatingFeedback}
                        className="btn btn-secondary"
                        style={{ padding: '0.5rem 1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}
                        title="AI analyzes wrong answers and creates an improvement plan for the student">
                        {generatingFeedback
                            ? <><Loader size={16} style={{ animation: 'spin 0.8s linear infinite' }} /> Generating…</>
                            : <><Sparkles size={16} /> AI Improvement Feedback</>}
                    </button>
                    <button
                        onClick={() => window.print()}
                        className="btn btn-primary"
                        style={{ padding: '0.5rem 1rem' }}>
                        Download PDF Report
                    </button>
                </div>
            </div>

            <div className="card report-card-print" style={{ padding: '3rem', position: 'relative', overflow: 'hidden' }}>
                <div style={{ position: 'absolute', top: 0, right: 0, padding: '2rem', opacity: 0.1 }}>
                    <Award size={100} color="var(--primary)" />
                </div>

                <div style={{ borderBottom: '2px solid var(--primary)', paddingBottom: '1.5rem', marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
                    <div>
                        <h2 style={{ fontSize: '2.5rem', marginBottom: '0.5rem', color: 'var(--text-main)' }}>Student Evaluation Report</h2>
                        <p style={{ color: 'var(--primary)', fontSize: '1.2rem', margin: 0, fontWeight: 600 }}>
                            MarkNex AI Personal Teacher Assistant
                        </p>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                        <div style={{ fontSize: '1.1rem', fontWeight: 600 }}>{script.grade}</div>
                        <div style={{ color: 'var(--text-muted)' }}>{script.exam}</div>
                    </div>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '2rem' }}>
                    <div>
                        <span style={{ display: 'block', color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '0.2rem' }}>STUDENT ID</span>
                        <strong style={{ fontSize: '1.3rem' }}>{script.student_id}</strong>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                        <span style={{ display: 'block', color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '0.2rem' }}>UPLOAD DATE</span>
                        <strong style={{ fontSize: '1.3rem' }}>{new Date(script.upload_timestamp).toLocaleDateString()}</strong>
                    </div>
                </div>

                {/* Official Evaluator's Seal & Summary */}
                <div style={{ 
                    background: '#0f172a', 
                    padding: '3.5rem 2rem', 
                    borderRadius: '28px', 
                    color: 'white', 
                    marginBottom: '3rem', 
                    position: 'relative', 
                    overflow: 'hidden',
                    boxShadow: '0 30px 60px -12px rgba(0,0,0,0.4)',
                    border: '1px solid rgba(255,255,255,0.1)'
                }}>
                    {/* Background Decorative Element */}
                    <div style={{ position: 'absolute', top: '-10%', right: '-5%', width: '40%', height: '120%', background: 'linear-gradient(45deg, transparent, rgba(56, 189, 248, 0.1))', transform: 'rotate(15deg)', pointerEvents: 'none' }} />
                    
                    <div style={{ position: 'relative', zIndex: 1 }}>
                        <div style={{ display: 'inline-block', background: 'rgba(56, 189, 248, 0.15)', padding: '0.6rem 1.5rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 800, color: '#38bdf8', letterSpacing: '2px', marginBottom: '1.5rem', border: '1px solid rgba(56, 189, 248, 0.3)' }}>
                            OFFICIAL ACADEMIC RECORD
                        </div>
                        
                        <div style={{ fontSize: '7rem', fontWeight: 900, lineHeight: 0.9, marginBottom: '0.5rem', display: 'flex', justifyContent: 'center', alignItems: 'flex-end', gap: '0.5rem' }}>
                            {script.total_marks}
                            <span style={{ fontSize: '2.5rem', color: '#64748b', fontWeight: 400, marginBottom: '1rem' }}>/{script.max_marks || 10}</span>
                        </div>
                        
                        <div style={{ display: 'flex', justifyContent: 'center', gap: '1.5rem', marginTop: '1.5rem', flexWrap: 'wrap' }}>
                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.4rem', padding: '1rem 2rem', background: 'rgba(255,255,255,0.03)', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)' }}>
                                <span style={{ color: '#94a3b8', fontSize: '0.75rem', fontWeight: 600 }}>STUDENT IDENTITY</span>
                                <span style={{ fontSize: '1.2rem', fontWeight: 700 }}>{script.student_id}</span>
                            </div>
                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.4rem', padding: '1rem 2rem', background: 'rgba(255,255,255,0.03)', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)' }}>
                                <span style={{ color: '#94a3b8', fontSize: '0.75rem', fontWeight: 600 }}>EXAMINATION</span>
                                <span style={{ fontSize: '1.2rem', fontWeight: 700 }}>{script.exam}</span>
                            </div>
                        </div>

                        <div style={{ marginTop: '2.5rem', display: 'flex', justifyContent: 'center', gap: '1rem' }}>
                            <div style={{ background: '#10b981', padding: '0.8rem 2rem', borderRadius: '50px', fontSize: '1rem', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '0.8rem', boxShadow: '0 15px 25px -5px rgba(16, 185, 129, 0.3)' }}>
                                <CheckCircle size={20} /> AI VERIFIED
                            </div>
                            {script.flags === 'Reviewed' && (
                                <div style={{ background: '#3b82f6', padding: '0.8rem 2rem', borderRadius: '50px', fontSize: '1rem', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '0.8rem', boxShadow: '0 15px 25px -5px rgba(59, 130, 246, 0.3)', border: '2px solid rgba(255,255,255,0.2)' }}>
                                    <Award size={22} /> TEACHER SIGNED
                                </div>
                            )}
                        </div>
                    </div>
                </div>

                <div>
                    <h3 style={{ borderBottom: '3px solid #1e293b', paddingBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '2.5rem', color: '#0f172a', fontWeight: 800, fontSize: '1.5rem' }}>
                        <CheckCircle size={24} color="#10b981" /> Performance Summary
                    </h3>
                    <p style={{ lineHeight: 1.8, fontSize: '1.2rem', color: '#334155', marginTop: '1rem', whiteSpace: 'pre-wrap', padding: '0 1rem' }}>
                        {script.report}
                    </p>
                    
                    <div style={{ marginTop: '3rem', padding: '2rem', background: '#f0f9ff', borderRadius: '16px', border: '1px solid #bae6fd', borderLeft: '6px solid #0284c7' }}>
                        <h4 style={{ margin: '0 0 0.8rem 0', color: '#0369a1', display: 'flex', alignItems: 'center', gap: '0.6rem', fontSize: '1.2rem' }}>
                            <Award size={20} /> Recommendations for Future Excellence
                        </h4>
                        <p style={{ margin: 0, color: '#0c4a6e', lineHeight: 1.6, fontSize: '1.05rem' }}>
                            {script.confidence_score > 90 
                                ? "Your understanding of core concepts is exceptional. To advance further, focus on synthesizing cross-modular themes and refining your technical vocabulary for more precise explanations." 
                                : "Focus on conceptual clarity and structured articulation. We recommend reviewing the specific annotated markings below to identify recurring patterns in deduction points."}
                        </p>
                    </div>

                    {/* Question-Wise Teacher Guidance Section */}
                    {questionsAnalysis && questionsAnalysis.length > 0 && (
                        <div style={{ marginTop: '3rem' }}>
                            <h3 style={{ margin: '0 0 1.5rem 0', color: '#1e293b', fontWeight: 800, fontSize: '1.4rem', display: 'flex', alignItems: 'center', gap: '0.8rem' }}>
                                <List size={22} color="var(--primary)" /> Question-by-Question Diagnostic
                            </h3>
                            <div style={{ display: 'grid', gap: '1rem' }}>
                                {questionsAnalysis.map((q, idx) => (
                                    <div key={idx} style={{ 
                                        padding: '1.2rem', 
                                        background: q.status === 'Correct' ? '#f0fdf4' : '#fff1f2', 
                                        borderRadius: '12px', 
                                        border: `1px solid ${q.status === 'Correct' ? '#bbf7d0' : '#fecdd3'}`,
                                        display: 'flex',
                                        gap: '1.2rem',
                                        alignItems: 'flex-start'
                                    }}>
                                        <div style={{ 
                                            background: q.status === 'Correct' ? '#22c55e' : '#ef4444',
                                            color: 'white',
                                            padding: '0.4rem 0.8rem',
                                            borderRadius: '8px',
                                            fontWeight: 700,
                                            fontSize: '0.9rem',
                                            minWidth: '50px',
                                            textAlign: 'center'
                                        }}>
                                            {q.q_num}
                                        </div>
                                        <div style={{ flex: 1 }}>
                                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                                                <span style={{ fontWeight: 700, color: q.status === 'Correct' ? '#166534' : '#991b1b' }}>{q.status}</span>
                                                <span style={{ fontWeight: 600, color: '#64748b' }}>Score: {q.marks_awarded} Marks</span>
                                            </div>
                                            {q.teacher_tip && (
                                                <p style={{ margin: 0, fontSize: '0.95rem', color: '#334155', fontStyle: 'italic', display: 'flex', gap: '0.5rem', alignItems: 'flex-start' }}>
                                                    <Lightbulb size={16} style={{ marginTop: '3px', flexShrink: 0, color: '#eab308' }} />
                                                    <strong>Teacher Guideline:</strong> {q.teacher_tip}
                                                </p>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                    
                    {aiCorrections && aiCorrections.length > 0 && (
                        <div className="report-section page-break" style={{ marginTop: '5rem' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2.5rem' }}>
                                <h3 style={{ margin: 0, color: '#0f172a', fontWeight: 900, fontSize: '1.8rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
                                    <AlertCircle size={32} color="#ef4444" strokeWidth={2.5} /> Permanently Marked Script
                                </h3>
                                <button 
                                    onClick={() => window.print()} 
                                    className="btn btn-primary" 
                                    style={{ display: 'flex', alignItems: 'center', gap: '0.8rem', padding: '0.8rem 1.5rem', borderRadius: '12px', fontWeight: 700, boxShadow: '0 10px 20px rgba(0,0,0,0.1)' }}
                                >
                                    <Download size={20} /> SAVE PERMANENT COPY
                                </button>
                            </div>
                            
                            {/* Precision Marking Viewer - Coordinate Locked */}
                            <div 
                                id="permanent-marking-viewport" 
                                style={{ 
                                    position: 'relative', 
                                    border: '2px solid #cbd5e1', 
                                    borderRadius: '20px', 
                                    overflow: 'hidden', 
                                    width: '100%',
                                    background: '#fff',
                                    boxShadow: '0 30px 60px -15px rgba(0, 0, 0, 0.2)',
                                    marginBottom: '5rem'
                                }}
                            >
                                <div style={{ 
                                    position: 'relative', 
                                    width: '100%', 
                                    minHeight: script.filepath.toLowerCase().endsWith('.pdf') ? '1400px' : 'auto',
                                    backgroundColor: 'white'
                                }}>
                                    {script.filepath.toLowerCase().endsWith('.pdf') ? (
                                        <div style={{ width: '100%', height: '1400px', position: 'relative' }}>
                                            <iframe 
                                                src={`${fileUrl(script.filepath)}#toolbar=0&navpanes=0&view=FitW`}
                                                style={{ width: '100%', height: '100%', border: 'none', display: 'block' }} 
                                                title="PDF Script"
                                            />
                                            {/* Permanent Labels Layer */}
                                            <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', pointerEvents: 'none' }}>
                                                {aiCorrections.map((corr, idx) => (
                                                    <div 
                                                        key={idx} 
                                                        style={{ 
                                                            position: 'absolute', 
                                                            top: `${corr.y}%`, 
                                                            left: `${corr.x}%`, 
                                                            transform: 'translate(-50%, -50%)', 
                                                            zIndex: 100
                                                        }} 
                                                    >
                                                        <div style={{
                                                            background: '#ef4444',
                                                            color: 'white',
                                                            width: '40px',
                                                            height: '40px',
                                                            fontSize: '22px',
                                                            borderRadius: '50%',
                                                            display: 'flex',
                                                            alignItems: 'center',
                                                            justifyContent: 'center',
                                                            fontWeight: 900,
                                                            boxShadow: '0 0 15px rgba(239, 68, 68, 0.8)',
                                                            border: '4px solid white',
                                                            pointerEvents: 'auto',
                                                            cursor: 'pointer'
                                                        }} onClick={() => setActiveMistake(idx)}>
                                                            {idx + 1}
                                                        </div>
                                                        {corr.correct_answer != null && corr.correct_answer !== '' && (
                                                            <div className="marker-dot" title={String(corr.correct_answer)} style={{
                                                                position: 'absolute', left: 'calc(100% + 6px)', top: '50%', transform: 'translateY(-50%)',
                                                                background: '#16a34a', color: 'white', padding: '3px 8px', borderRadius: '6px',
                                                                fontSize: '13px', fontWeight: 800, whiteSpace: 'nowrap', maxWidth: '220px',
                                                                overflow: 'hidden', textOverflow: 'ellipsis', boxShadow: '0 3px 8px rgba(0,0,0,0.35)',
                                                                border: '1px solid white', pointerEvents: 'none'
                                                            }}>
                                                                ✓ {corr.correct_answer}
                                                            </div>
                                                        )}
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ) : (
                                        <div style={{ position: 'relative' }}>
                                            <img 
                                                src={fileUrl(script.filepath)}
                                                alt="Marked Paper"
                                                style={{ display: 'block', width: '100%', height: 'auto' }} 
                                            />
                                            <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', pointerEvents: 'none' }}>
                                                {aiCorrections.map((corr, idx) => (
                                                    <div 
                                                        key={idx} 
                                                        style={{ 
                                                            position: 'absolute', 
                                                            top: `${corr.y}%`, 
                                                            left: `${corr.x}%`, 
                                                            transform: 'translate(-50%, -50%)', 
                                                            zIndex: 20
                                                        }} 
                                                    >
                                                        <div style={{
                                                            background: '#ef4444',
                                                            color: 'white',
                                                            width: '40px',
                                                            height: '40px',
                                                            fontSize: '22px',
                                                            borderRadius: '50%',
                                                            display: 'flex',
                                                            alignItems: 'center',
                                                            justifyContent: 'center',
                                                            fontWeight: 900,
                                                            boxShadow: '0 5px 15px rgba(239, 68, 68, 0.6)',
                                                            border: '4px solid white',
                                                            cursor: 'pointer',
                                                            pointerEvents: 'auto'
                                                        }} onClick={() => setActiveMistake(idx)}>
                                                            {idx + 1}
                                                        </div>
                                                        {corr.correct_answer != null && corr.correct_answer !== '' && (
                                                            <div className="marker-dot" title={String(corr.correct_answer)} style={{
                                                                position: 'absolute', left: 'calc(100% + 6px)', top: '50%', transform: 'translateY(-50%)',
                                                                background: '#16a34a', color: 'white', padding: '3px 8px', borderRadius: '6px',
                                                                fontSize: '13px', fontWeight: 800, whiteSpace: 'nowrap', maxWidth: '220px',
                                                                overflow: 'hidden', textOverflow: 'ellipsis', boxShadow: '0 3px 8px rgba(0,0,0,0.35)',
                                                                border: '1px solid white', pointerEvents: 'none'
                                                            }}>
                                                                ✓ {corr.correct_answer}
                                                            </div>
                                                        )}
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>

                            {/* Categorical Analysis Ledger */}
                            <div className="report-section page-break" style={{ background: '#f8fafc', padding: '3rem', borderRadius: '32px', border: '1px solid #e2e8f0' }}>
                                <h4 style={{ margin: '0 0 3rem 0', color: '#0f172a', fontSize: '1.8rem', fontWeight: 900, letterSpacing: '-0.7px', borderLeft: '10px solid #ef4444', paddingLeft: '1.5rem' }}>
                                    Evaluation Matrix & Detailed Feedback
                                </h4>
                                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                                    {aiCorrections.map((corr, idx) => (
                                        <div 
                                            key={idx} 
                                            style={{ 
                                                display: 'grid',
                                                gridTemplateColumns: '70px 1fr',
                                                gap: '3rem',
                                                padding: '2.5rem', 
                                                borderRadius: '24px', 
                                                background: activeMistake === idx ? '#fff' : 'rgba(255,255,255,0.7)',
                                                border: activeMistake === idx ? '3px solid #ef4444' : '1px solid #e2e8f0',
                                                transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                                                cursor: 'pointer',
                                                boxShadow: activeMistake === idx ? '0 30px 45px -15px rgba(239, 68, 68, 0.25)' : '0 4px 6px rgba(0,0,0,0.02)'
                                            }}
                                            onClick={() => setActiveMistake(idx)}
                                        >
                                            <div style={{ 
                                                background: activeMistake === idx ? '#ef4444' : '#0f172a', 
                                                color: 'white', 
                                                width: '60px', 
                                                height: '60px',
                                                minHeight: '60px',
                                                borderRadius: '16px', 
                                                display: 'flex', 
                                                alignItems: 'center', 
                                                justifyContent: 'center', 
                                                fontSize: '2rem',
                                                fontWeight: 900,
                                                boxShadow: '0 8px 15px rgba(0,0,0,0.1)'
                                            }}>
                                                {idx + 1}
                                            </div>
                                            <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '0.8rem' }}>
                                                <div style={{ color: '#1e293b', fontSize: '1.5rem', fontWeight: 600, lineHeight: 1.4 }}>
                                                    {corr.text}
                                                </div>
                                                {corr.correct_answer != null && corr.correct_answer !== '' && (
                                                    <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.8rem', background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '14px', padding: '1rem 1.4rem' }}>
                                                        <CheckCircle size={22} color="#16a34a" style={{ marginTop: '2px', flexShrink: 0 }} />
                                                        <div>
                                                            <span style={{ display: 'block', fontSize: '0.8rem', fontWeight: 800, color: '#15803d', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '0.2rem' }}>Correct Answer</span>
                                                            <span style={{ color: '#166534', fontSize: '1.2rem', fontWeight: 600, lineHeight: 1.4 }}>{corr.correct_answer}</span>
                                                        </div>
                                                    </div>
                                                )}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                            
                            <div style={{ marginTop: '7rem', padding: '4rem', borderTop: '6px solid #f1f5f9', textAlign: 'center' }}>
                                <div style={{ color: '#94a3b8', fontSize: '1.1rem', marginBottom: '1.2rem', fontWeight: 800, letterSpacing: '5px', textTransform: 'uppercase' }}>Official Academic Transcript</div>
                                <div style={{ fontSize: '1.8rem', fontWeight: 900, color: '#0f172a', marginBottom: '0.6rem' }}>MarkNex AI Intelligence Engineering</div>
                                <div style={{ color: '#cbd5e1', fontSize: '1.2rem', fontWeight: 500 }}>Certificate of Evaluation ID: MK-{script.id}-{new Date().getTime().toString().slice(-10)}</div>
                            </div>
                        </div>
                    )}
                </div>

            </div>
        </div>
    );
}

export default Report;
